INSERT INTO MOVIES (ID, NAME, IMG, TRAILER_URL, YEAR, COUNTRY, LANGUAGE, GENRES, STARRING, DIRECTOR, WRITTEN_BY, RELEASE_DATE, MOVIE_TIMING, AGE_LIMIT, SYNOPSIS) VALUES (
'1',
'Blade runner 2049',
'/img/soon1.png',
'https://www.youtube.com/watch?v=gCcx85zbxz4','2019',
'USA',
'English',
'Biography/Crime/Drama',
'Robert De Niro, Al Pacino, Joe Pesci',
'Martin Scorsese',
'Steven Zaillian (screenplay)/Charles Brandt (book)',
{ts '2020-11-12 18:47:52.69'},
'3h 29min',
'+16',
'Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam,purus sit amet luctus venenatis, lectus magna fringilla urna, porttitorrhoncus dolor purus non enim praesent elementum');

INSERT INTO MOVIES (ID, NAME, IMG, TRAILER_URL, YEAR, COUNTRY, LANGUAGE, GENRES, STARRING, DIRECTOR, WRITTEN_BY, RELEASE_DATE, MOVIE_TIMING, AGE_LIMIT, SYNOPSIS)
VALUES (2,
'Attack on Titan',
'/img/soon2.png',
'https://www.youtube.com/watch?v=gCcx85zbxz4',
'2019',
'USA',
'English',
'Biography/Crime/Drama',
'Robert De Niro, Al Pacino, Joe Pesci',
'Martin Scorsese',
'Steven Zaillian (screenplay)/Charles Brandt (book)',
{ts '2020-11-12 18:47:52.69'},
'3h 29min',
'+16',
'Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam,purus sit amet luctus venenatis, lectus magna fringilla urna, porttitorrhoncus dolor purus non enim praesent elementum');

INSERT INTO MOVIES (ID, NAME, IMG, TRAILER_URL, YEAR, COUNTRY, LANGUAGE, GENRES, STARRING, DIRECTOR, WRITTEN_BY, RELEASE_DATE, MOVIE_TIMING, AGE_LIMIT, SYNOPSIS)
VALUES (3,
'Monster',
'/img/soon3.png',
'https://www.youtube.com/watch?v=gCcx85zbxz4',
'2019',
'USA',
'English',
'Biography/Crime/Drama',
'Robert De Niro, Al Pacino, Joe Pesci',
'Martin Scorsese',
'Steven Zaillian (screenplay)/Charles Brandt (book)',
{ts '2020-11-12 18:47:52.69'},
'3h 29min',
'+16',
'Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam,purus sit amet luctus venenatis, lectus magna fringilla urna, porttitorrhoncus dolor purus non enim praesent elementum');

INSERT INTO MOVIES (ID, NAME, IMG, TRAILER_URL, YEAR, COUNTRY, LANGUAGE, GENRES, STARRING, DIRECTOR, WRITTEN_BY, RELEASE_DATE, MOVIE_TIMING, AGE_LIMIT, SYNOPSIS)
VALUES (4,
'March Comes in like a lion',
'/img/soon4.png',
'https://www.youtube.com/watch?v=gCcx85zbxz4',
'2019',
'USA',
'English',
'Biography/Crime/Drama',
'Robert De Niro, Al Pacino, Joe Pesci',
'Martin Scorsese',
'Steven Zaillian (screenplay)/Charles Brandt (book)',
{ts '2020-11-17 18:47:52.69'},
'3h 29min',
'+16',
'Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam,purus sit amet luctus venenatis, lectus magna fringilla urna, porttitorrhoncus dolor purus non enim praesent elementum');

INSERT INTO MOVIES (ID, NAME, IMG, TRAILER_URL, YEAR, COUNTRY, LANGUAGE, GENRES, STARRING, DIRECTOR, WRITTEN_BY, RELEASE_DATE, MOVIE_TIMING, AGE_LIMIT, SYNOPSIS)
VALUES (5,
'Reservoir Dogs',
'/img/soon5.png',
'https://www.youtube.com/watch?v=gCcx85zbxz4',
'2019',
'USA',
'English',
'Biography/Crime/Drama',
'Robert De Niro, Al Pacino, Joe Pesci',
'Martin Scorsese',
'Steven Zaillian (screenplay)/Charles Brandt (book)',
{ts '2020-11-17 18:47:52.69'},
'3h 29min',
'+16',
'Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam,purus sit amet luctus venenatis, lectus magna fringilla urna, porttitorrhoncus dolor purus non enim praesent elementum');

INSERT INTO MOVIES (ID, NAME, IMG, TRAILER_URL, YEAR, COUNTRY, LANGUAGE, GENRES, STARRING, DIRECTOR, WRITTEN_BY, RELEASE_DATE, MOVIE_TIMING, AGE_LIMIT, SYNOPSIS)
VALUES (6,
'Nier Automata',
'/img/soon6.png',
'https://www.youtube.com/watch?v=gCcx85zbxz4',
'2019',
'USA',
'English',
'Biography/Crime/Drama',
'Robert De Niro, Al Pacino, Joe Pesci',
'Martin Scorsese',
'Steven Zaillian (screenplay)/Charles Brandt (book)',
{ts '2020-11-17 18:47:52.69'},
'3h 29min',
'+16',
'Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam,purus sit amet luctus venenatis, lectus magna fringilla urna, porttitorrhoncus dolor purus non enim praesent elementum');

INSERT INTO MOVIES (ID, NAME, IMG, TRAILER_URL, YEAR, COUNTRY, LANGUAGE, GENRES, STARRING, DIRECTOR, WRITTEN_BY, RELEASE_DATE, MOVIE_TIMING, AGE_LIMIT, SYNOPSIS)
VALUES (7,
'The Heteful Eight',
'/img/soon7.png',
'https://www.youtube.com/watch?v=gCcx85zbxz4',
'2019',
'USA',
'English',
'Biography/Crime/Drama',
'Robert De Niro, Al Pacino, Joe Pesci',
'Martin Scorsese',
'Steven Zaillian (screenplay)/Charles Brandt (book)',
{ts '2020-11-17 18:47:52.69'},
'3h 29min',
'+16',
'Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam,purus sit amet luctus venenatis, lectus magna fringilla urna, porttitorrhoncus dolor purus non enim praesent elementum');

INSERT INTO MOVIES (ID, NAME, IMG, TRAILER_URL, YEAR, COUNTRY, LANGUAGE, GENRES, STARRING, DIRECTOR, WRITTEN_BY, RELEASE_DATE, MOVIE_TIMING, AGE_LIMIT, SYNOPSIS)
VALUES (8,
'Django Unchained',
'/img/soon8.png',
'https://www.youtube.com/watch?v=gCcx85zbxz4',
'2019',
'USA',
'English',
'Biography/Crime/Drama',
'Robert De Niro, Al Pacino, Joe Pesci',
'Martin Scorsese',
'Steven Zaillian (screenplay)/Charles Brandt (book)',
{ts '2020-11-17 18:47:52.69'},
'3h 29min',
'+16',
'Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam,purus sit amet luctus venenatis, lectus magna fringilla urna, porttitorrhoncus dolor purus non enim praesent elementum');

INSERT INTO MOVIES (ID, NAME, IMG, TRAILER_URL, YEAR, COUNTRY, LANGUAGE, GENRES, STARRING, DIRECTOR, WRITTEN_BY, RELEASE_DATE, MOVIE_TIMING, AGE_LIMIT, SYNOPSIS)
VALUES (9,
'Evangelion',
'/img/soon9.png',
'https://www.youtube.com/watch?v=gCcx85zbxz4',
'2019',
'USA',
'English',
'Biography/Crime/Drama',
'Robert De Niro, Al Pacino, Joe Pesci',
'Martin Scorsese',
'Steven Zaillian (screenplay)/Charles Brandt (book)',
{ts '2020-11-12 18:47:52.69'},
'3h 29min',
'+16',
'Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam,purus sit amet luctus venenatis, lectus magna fringilla urna, porttitorrhoncus dolor purus non enim praesent elementum');

INSERT INTO MOVIES (ID, NAME, IMG, TRAILER_URL, YEAR, COUNTRY, LANGUAGE, GENRES, STARRING, DIRECTOR, WRITTEN_BY, RELEASE_DATE, MOVIE_TIMING, AGE_LIMIT, SYNOPSIS)
VALUES (10,
'The Heteful Eight',
'/img/soon10.png',
'https://www.youtube.com/watch?v=gCcx85zbxz4',
'2019',
'USA',
'English',
'Biography/Crime/Drama',
'Robert De Niro, Al Pacino, Joe Pesci',
'Martin Scorsese',
'Steven Zaillian (screenplay)/Charles Brandt (book)',
{ts '2020-11-12 18:47:52.69'},
'3h 29min',
'+16',
'Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam,purus sit amet luctus venenatis, lectus magna fringilla urna, porttitorrhoncus dolor purus non enim praesent elementum');
